In [241]:
import nltk

from os import getcwd
import numpy as np
import pandas as pd
from nltk.corpus import twitter_samples

In [242]:
nltk.download('twitter_samples')
nltk.download('stopwords')

[nltk_data] Downloading package twitter_samples to
[nltk_data]     C:\Users\Winzyl\AppData\Roaming\nltk_data...
[nltk_data]   Package twitter_samples is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Winzyl\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [243]:
import json

with open('C:/Users/Winzyl/Desktop/migrate/fildata/POSv2.json') as f:
  pos = json.load(f)

with open('C:/Users/Winzyl/Desktop/migrate/fildata/NEGv2.json') as f:
  neg = json.load(f)

In [244]:
filePath = f"{getcwd()}/../tmp2/"
nltk.data.path.append(filePath)

In [245]:
stopwords_filipino = ["akin","aking","ako","alin","am","amin","aming","ang","ano","anumang","apat","at","atin","ating","ay","bababa","bago","bakit","bawat","bilang","dahil","dalawa","dapat","din","dito","doon","gagawin","gayunman","ginagawa","ginawa","ginawang","gumawa","gusto","habang","hanggang","hindi","huwag","iba","ibaba","ibabaw","ibig","ikaw","ilagay","ilalim","ilan","inyong","isa","isang","itaas","ito","iyo","iyon","iyong","ka","kahit","kailangan","kailanman","kami","kanila","kanilang","kanino","kanya","kanyang","kapag","kapwa","karamihan","katiyakan","katulad","kaya","kaysa","ko","kong","kulang","kumuha","kung","laban","lahat","lamang","likod","lima","maaari","maaaring","maging","mahusay","makita","marami","marapat","masyado","may","mayroon","mga","minsan","mismo","mula","muli","na","nabanggit","naging","nagkaroon","nais","nakita","namin","napaka","narito","nasaan","ng","ngayon","ni","nila","nilang","nito","niya","niyang","noon","o","pa","paano","pababa","paggawa","pagitan","pagkakaroon","pagkatapos","palabas","pamamagitan","panahon","pangalawa","para","paraan","pareho","pataas","pero","pumunta","pumupunta","sa","saan","sabi","sabihin","sarili","sila","sino","siya","tatlo","tayo","tulad","tungkol","una","walang"]

In [246]:
nltk.download('stopwords')
from nltk.corpus import stopwords
taglish = stopwords.words('english') + stopwords_filipino
print(taglish)

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're", "you've", "you'll", "you'd", 'your', 'yours', 'yourself', 'yourselves', 'he', 'him', 'his', 'himself', 'she', "she's", 'her', 'hers', 'herself', 'it', "it's", 'its', 'itself', 'they', 'them', 'their', 'theirs', 'themselves', 'what', 'which', 'who', 'whom', 'this', 'that', "that'll", 'these', 'those', 'am', 'is', 'are', 'was', 'were', 'be', 'been', 'being', 'have', 'has', 'had', 'having', 'do', 'does', 'did', 'doing', 'a', 'an', 'the', 'and', 'but', 'if', 'or', 'because', 'as', 'until', 'while', 'of', 'at', 'by', 'for', 'with', 'about', 'against', 'between', 'into', 'through', 'during', 'before', 'after', 'above', 'below', 'to', 'from', 'up', 'down', 'in', 'out', 'on', 'off', 'over', 'under', 'again', 'further', 'then', 'once', 'here', 'there', 'when', 'where', 'why', 'how', 'all', 'any', 'both', 'each', 'few', 'more', 'most', 'other', 'some', 'such', 'no', 'nor', 'not', 'only', 'own', 'same', 'so', 'than', '

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Winzyl\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [247]:
import re
import string
import numpy as np

from nltk.corpus import stopwords
from nltk.stem import PorterStemmer
from nltk.tokenize import TweetTokenizer


def process_tweet(tweet):
    """Process tweet function.
    Input:
        tweet: a string containing a tweet
    Output:
        tweets_clean: a list of words containing the processed tweet
    """
    stemmer = PorterStemmer()
    stopwords_english = taglish
    # remove stock market tickers like $GE
    tweet = re.sub(r'\$\w*', '', tweet)
    # remove old style retweet text "RT"
    tweet = re.sub(r'^RT[\s]+', '', tweet)
    # remove links
    tweet = re.sub(r'https?:\/\/.*[\r\n]*', '', tweet)
    # remove hashtags
    tweet = re.sub(r'#', '', tweet)
    # tokenize
    tokenizer = TweetTokenizer(preserve_case=False, strip_handles=True,
                               reduce_len=True)
    tweet_tokens = tokenizer.tokenize(tweet)

    tweets_clean = []
    for word in tweet_tokens:
        if (word not in stopwords_english and  # remove stopwords
                word not in string.punctuation):  # remove punctuation
            # tweets_clean.append(word)
            stem_word = stemmer.stem(word)  # stemming word
            tweets_clean.append(stem_word)

    return tweets_clean


def build_freqs(tweets, ys):
    """Build frequencies.
    Input:
        tweets: a list of tweets
        ys: an m x 1 array with the sentiment label of each tweet
            (either 0 or 1)
    Output:
        freqs: a dictionary mapping each (word, sentiment) pair to its
        frequency
    """
    # Convert np array to list since zip needs an iterable.
    # The squeeze is necessary or the list ends up with one element.
    yslist = np.squeeze(ys).tolist()

    # Start with an empty dictionary and provide data by looping all tweets
    freqs = {}
    for y, tweet in zip(yslist, tweets):
        for word in process_tweet(tweet):
            pair = (word, y)
            if pair in freqs:
                freqs[pair] += 1
            else:
                freqs[pair] = 1

    return freqs

In [248]:
all_positive_tweets = pos
all_negative_tweets = neg

In [249]:
print(len(all_positive_tweets))
print(len(all_negative_tweets))

3339
3072


In [250]:
#2774p os
#2032 neg

test_pos = all_positive_tweets[2400:]

train_pos = all_positive_tweets[:3000]

test_neg = all_negative_tweets[2400:]

train_neg = all_negative_tweets[:3000]


train_x = train_pos + train_neg 
test_x = test_pos + test_neg

In [251]:
print(len(test_pos))
print(len(train_pos))
print(len(test_neg))
print(len(train_neg))

939
3000
672
3000


In [252]:
print(process_tweet(train_x[4]))

['lang', 'alreadi', 'admir', 'presidenti', 'candid', 'courag', 'show', 'cnnphpresidentialdeb']


In [253]:
train_y = np.append(np.ones((len(train_pos), 1)), np.zeros((len(train_neg), 1)), axis=0)
test_y = np.append(np.ones((len(test_pos), 1)), np.zeros((len(test_neg), 1)), axis=0)

In [254]:
print(train_y)

[[1.]
 [1.]
 [1.]
 ...
 [0.]
 [0.]
 [0.]]


In [255]:
print("train_y.shape = " + str(train_y.shape))
print("test_y.shape = " + str(test_y.shape))

train_y.shape = (6000, 1)
test_y.shape = (1611, 1)


In [256]:
freqs = build_freqs(train_x, train_y)

print("type(freqs) = " + str(type(freqs)))
print("len(freqs) = " + str(len(freqs.keys())))

type(freqs) = <class 'dict'>
len(freqs) = 15706


In [257]:
print('raw data: \n', train_x[2])
print('\nprocessed data: \n', process_tweet(train_x[2]))

raw data: 
 Going to watch Mayor Isko Moreno Domagoso on #CNNPHPresidentialDebate .
#SwitchToIsko

processed data: 
 ['go', 'watch', 'mayor', 'isko', 'moreno', 'domagoso', 'cnnphpresidentialdeb', 'switchtoisko']


In [258]:
# UNQ_C1 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def sigmoid(z): 
    '''
    Input:
        z: is the input (can be a scalar or an array)
    Output:
        h: the sigmoid of z
    '''
    
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    # calculate the sigmoid of z
    h = 1/(1+np.exp(-z))
    ### END CODE HERE ###
    
    return h

In [259]:
if (sigmoid(0) == 0.5):
    print('works')
else:
    print('err')

if (sigmoid(4.92) == 0.9927537604041685):
    print('works')
else:
    print('err')

works
works


In [260]:
-1 * (1 - 0) * np.log(1 - 0.9999) # loss is about 9.2

9.210340371976294

In [261]:
# UNQ_C2 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def gradientDescent(x, y, theta, alpha, num_iters):
    '''
    Input:
        x: matrix of features which is (m,n+1)
        y: corresponding labels of the input matrix x, dimensions (m,1)
        theta: weight vector of dimension (n+1,1)
        alpha: learning rate
        num_iters: number of iterations you want to train your model for
    Output:
        J: the final cost
        theta: your final weight vector
    Hint: you might want to print the cost to make sure that it is going down.
    '''
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    # get 'm', the number of rows in matrix x
    m = x.shape[0]
    
    for i in range(0, num_iters):
        
        # get z, the dot product of x and theta
        z = np.dot(x,theta)
        
        # get the sigmoid of z
        h = sigmoid(z)
        
        # calculate the cost function
        J = -1./m * (np.dot(y.transpose(), np.log(h)) + np.dot((1-y).transpose(),np.log(1-h)))
        print(J)
        # update the weights theta
        theta = theta - (alpha/m) * np.dot(x.transpose(),(h-y))
        
    ### END CODE HERE ###
    J = float(J)
    return J, theta


In [262]:
# using numpy PRNG functions
np.random.seed(1)
# X input is 10 x 3 with ones for the bias terms
tmp_X = np.append(np.ones((10, 1)), np.random.rand(10, 2) * 2000, axis=1)
# Y Labels are 10 x 1
tmp_Y = (np.random.rand(10, 1) > 0.35).astype(float)

# gradient descent
tmp_J, tmp_theta = gradientDescent(tmp_X, tmp_Y, np.zeros((3, 1)), 1e-8, 700)
print(f"The cost for training is {tmp_J:.8f}.")
print(f"The resulting vector of weight is {[round(t, 8) for t in np.squeeze(tmp_theta)]}")

[[0.69314718]]
[[0.69305407]]
[[0.69296151]]
[[0.6928695]]
[[0.69277802]]
[[0.69268708]]
[[0.69259667]]
[[0.69250679]]
[[0.69241743]]
[[0.69232859]]
[[0.69224027]]
[[0.69215246]]
[[0.69206515]]
[[0.69197836]]
[[0.69189206]]
[[0.69180626]]
[[0.69172096]]
[[0.69163614]]
[[0.69155182]]
[[0.69146797]]
[[0.69138461]]
[[0.69130172]]
[[0.6912193]]
[[0.69113736]]
[[0.69105588]]
[[0.69097486]]
[[0.6908943]]
[[0.6908142]]
[[0.69073455]]
[[0.69065535]]
[[0.69057659]]
[[0.69049828]]
[[0.69042041]]
[[0.69034297]]
[[0.69026597]]
[[0.6901894]]
[[0.69011325]]
[[0.69003753]]
[[0.68996223]]
[[0.68988734]]
[[0.68981287]]
[[0.68973881]]
[[0.68966516]]
[[0.68959192]]
[[0.68951908]]
[[0.68944664]]
[[0.68937459]]
[[0.68930294]]
[[0.68923168]]
[[0.68916081]]
[[0.68909032]]
[[0.68902022]]
[[0.6889505]]
[[0.68888115]]
[[0.68881218]]
[[0.68874358]]
[[0.68867534]]
[[0.68860748]]
[[0.68853998]]
[[0.68847284]]
[[0.68840605]]
[[0.68833963]]
[[0.68827355]]
[[0.68820783]]
[[0.68814245]]
[[0.68807742]]
[[0.68801274]]
[

In [263]:
# UNQ_C3 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def extract_features(tweet, freqs):
    '''
    Input: 
        tweet: a list of words for one tweet
        freqs: a dictionary corresponding to the frequencies of each tuple (word, label)
    Output: 
        x: a feature vector of dimension (1,3)
    '''
    # process_tweet tokenizes, stems, and removes stopwords
    word_l = process_tweet(tweet)
    
    # 3 elements in the form of a 1 x 3 vector
    x = np.zeros((1, 3)) 
    
    #bias term is set to 1
    x[0,0] = 1 
    
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    
    # loop through each word in the list of words
    for word in word_l:
        
        # increment the word count for the positive label 1
        x[0,1] += freqs.get((word, 1.0),0)
        
        # increment the word count for the negative label 0
        x[0,2] += freqs.get((word, 0.0),0)
        
    ### END CODE HERE ###
    assert(x.shape == (1, 3))
    return x

In [264]:
#test 1
tmp1 = extract_features(train_x[0], freqs)
print(tmp1)

[[  1. 785. 606.]]


In [265]:
# test 2
tmp2 = extract_features('blorb bleeeeb bloooob', freqs)
print(tmp2)

[[1. 0. 0.]]


In [266]:
print(np.zeros((3, 1)))

[[0.]
 [0.]
 [0.]]


In [267]:
X = np.zeros((len(train_x), 3))#array structure
for i in range(len(train_x)):#loop through train x to extract features on each
    X[i, :]= extract_features(train_x[i], freqs)

Y = train_y # training labels

J, theta = gradientDescent(X, Y, np.zeros((3, 1)), 1e-9, 1500)
print(f"The cost after training is {J:.8f}.")
print(f"The resulting vector of weights is {[round(t, 8) for t in np.squeeze(theta)]}")

[[0.69314718]]
[[0.69306387]]
[[0.69298094]]
[[0.6928984]]
[[0.69281625]]
[[0.69273447]]
[[0.69265308]]
[[0.69257206]]
[[0.69249141]]
[[0.69241114]]
[[0.69233124]]
[[0.69225171]]
[[0.69217254]]
[[0.69209374]]
[[0.6920153]]
[[0.69193723]]
[[0.69185951]]
[[0.69178215]]
[[0.69170514]]
[[0.69162849]]
[[0.69155219]]
[[0.69147623]]
[[0.69140063]]
[[0.69132537]]
[[0.69125046]]
[[0.69117588]]
[[0.69110165]]
[[0.69102775]]
[[0.69095419]]
[[0.69088097]]
[[0.69080808]]
[[0.69073552]]
[[0.69066329]]
[[0.69059138]]
[[0.6905198]]
[[0.69044855]]
[[0.69037761]]
[[0.690307]]
[[0.69023671]]
[[0.69016673]]
[[0.69009707]]
[[0.69002772]]
[[0.68995868]]
[[0.68988995]]
[[0.68982153]]
[[0.68975342]]
[[0.68968561]]
[[0.68961811]]
[[0.6895509]]
[[0.689484]]
[[0.68941739]]
[[0.68935109]]
[[0.68928507]]
[[0.68921935]]
[[0.68915393]]
[[0.68908879]]
[[0.68902394]]
[[0.68895938]]
[[0.6888951]]
[[0.68883111]]
[[0.6887674]]
[[0.68870397]]
[[0.68864082]]
[[0.68857795]]
[[0.68851535]]
[[0.68845303]]
[[0.68839099]]
[[0.6

In [268]:
def predict_tweet(tweet, freqs, theta):
    '''
    Input: 
        tweet: a string
        freqs: a dictionary corresponding to the frequencies of each tuple (word, label)
        theta: (3,1) vector of weights
    Output: 
        y_pred: the probability of a tweet being positive or negative
    '''
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    
    # extract the features of the tweet and store it into x
    x = extract_features(tweet,freqs)
    
    # make the prediction using x and theta
    y_pred =sigmoid(np.dot(x,theta))
    
    ### END CODE HERE ###
    
    return y_pred

In [269]:
for tweet in ['ako ay masayang masaya', 'ikaw ay masama', 'talgang natuwa ako', 'salamat', 'salamat salamat', 'salamat salamat salamat']:
    print( '%s -> %f' % (tweet, predict_tweet(tweet, freqs, theta)))

ako ay masayang masaya -> 0.500102
ikaw ay masama -> 0.500058
talgang natuwa ako -> 0.500000
salamat -> 0.501415
salamat salamat -> 0.502831
salamat salamat salamat -> 0.504246


In [270]:
positive = 'masaya ako ngayon'
predict_tweet(positive, freqs, theta)

array([[0.49997819]])

In [271]:
negative = 'galit ako ngayon'
predict_tweet(negative, freqs, theta)

array([[0.49964892]])

In [272]:
# UNQ_C5 (UNIQUE CELL IDENTIFIER, DO NOT EDIT)
def test_logistic_regression(test_x, test_y, freqs, theta):
    """
    Input: 
        test_x: a list of tweets
        test_y: (m, 1) vector with the corresponding labels for the list of tweets
        freqs: a dictionary with the frequency of each pair (or tuple)
        theta: weight vector of dimension (3, 1)
    Output: 
        accuracy: (# of tweets classified correctly) / (total # of tweets)
    """
    
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    
    # the list for storing predictions
    y_hat = []
    
    for tweet in test_x:
        # get the label prediction for the tweet
        y_pred = predict_tweet(tweet, freqs, theta)
        
        if y_pred > 0.5:
            # append 1.0 to the list
            y_hat.append(1)
        else:
            # append 0 to the list
            y_hat.append(0)

    # With the above implementation, y_hat is a list, but test_y is (m,1) array
    # convert both to one-dimensional arrays in order to compare them using the '==' operator
    accuracy = (y_hat==np.squeeze(test_y)).sum()/len(test_x)
    print(f"Total True Prediction: {(y_hat==np.squeeze(test_y)).sum()}")
    print(f"total number of predictions: {len(test_x)}")

    ### END CODE HERE ###
    
    return accuracy

In [273]:
def test_precision(test_x, test_y, freqs, theta):
    
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    
    # the list for storing predictions
    y_hat = []
    x_hat = []
    
    for tweet in test_x:
        # get the label prediction for the tweet
        y_pred = predict_tweet(tweet, freqs, theta)
        
        if y_pred > 0.5 and tweet in test_pos: #true positive
            y_hat.append(1)
        else:
            # append 0 to the list
            y_hat.append(0)

    for tweet in test_x:
        # get the label prediction for the tweet
        y_pred = predict_tweet(tweet, freqs, theta)
        
        if y_pred > 0.5 and tweet in test_pos: #true positive
            x_hat.append(1)
        
        if y_pred > 0.5 and tweet not in test_pos: #false positive
            x_hat.append(1)

        else:
            # append 0 to the list
            x_hat.append(0)
            
    # With the above implementation, y_hat is a list, but test_y is (m,1) array
    # convert both to one-dimensional arrays in order to compare them using the '==' operator
    presision = (sum(y_hat)/sum(x_hat))
    print(f"TRUE positives: {sum(y_hat)}")
    print(f"total predicted positives: {sum(x_hat)}")

    ### END CODE HERE ###
    
    return presision

In [274]:
def test_recall(test_x, test_y, freqs, theta):
    
    ### START CODE HERE (REPLACE INSTANCES OF 'None' with your code) ###
    
    # the list for storing predictions
    y_hat = []
    x_hat = []
    
    for tweet in test_x:
        # get the label prediction for the tweet
        y_pred = predict_tweet(tweet, freqs, theta)
        
        if y_pred > 0.5 and tweet in test_pos: #true positive
            y_hat.append(1)
        else:
            # append 0 to the list
            y_hat.append(0)

    for tweet in test_x:
        # get the label prediction for the tweet
        y_pred = predict_tweet(tweet, freqs, theta)
        
        if y_pred > 0.5 and tweet in test_pos: #true positive
            x_hat.append(1)
        
        if y_pred < 0.5 and tweet not in test_neg: #false negative
            x_hat.append(1)

        else:
            # append 0 to the list
            x_hat.append(0)
            
    # With the above implementation, y_hat is a list, but test_y is (m,1) array
    # convert both to one-dimensional arrays in order to compare them using the '==' operator
    recall = (sum(y_hat)/sum(x_hat))
    print(f"TRUE positives: {sum(y_hat)}")
    print(f"total actual positive: {sum(x_hat)}")

    ### END CODE HERE ###
    
    return recall

In [275]:
tmp_recall = test_recall(test_x, test_y, freqs, theta)
print(f"Logistic regression model's recall = {tmp_recall:.4f}")

TRUE positives: 654
total actual positive: 939
Logistic regression model's recall = 0.6965


In [276]:
tmp_precision = test_precision(test_x, test_y, freqs, theta)
print(f"Logistic regression model's precision = {tmp_precision:.4f}")

TRUE positives: 654
total predicted positives: 681
Logistic regression model's precision = 0.9604


In [277]:
tmp_accuracy = test_logistic_regression(test_x, test_y, freqs, theta)
print(f"Logistic regression model's accuracy = {tmp_accuracy:.4f}")

Total True Prediction: 1299
total number of predictions: 1611
Logistic regression model's accuracy = 0.8063


In [278]:
print('Label Predicted Tweet')
for x,y in zip(test_x,test_y):
    y_hat = predict_tweet(x, freqs, theta)

    if np.abs(y - (y_hat > 0.5)) > 0:
        print('Raw data:', x)
        print('Processed data:', process_tweet(x))
        print('%d\t%0.8f\t%s' % (y, y_hat, ' '.join(process_tweet(x)).encode('ascii', 'ignore')))

Label Predicted Tweet
Raw data: Ayan buti naman may delicadeza siya. #comelec #CommissionOrElection https://t.co/gYYWineHTA
Processed data: ['ayan', 'buti', 'naman', 'delicadeza', 'comelec', 'commissionorelect']
1	0.49627592	b'ayan buti naman delicadeza comelec commissionorelect'
Raw data: Whats happening?? wala naman masama sa live stream eh.. mas ok nga yun para walang dayaan. Im not a registered voter, but I still have voice? #comelec
Processed data: ['what', 'happen', 'wala', 'naman', 'masama', 'live', 'stream', 'eh', '..', 'ma', 'ok', 'nga', 'yun', 'dayaan', 'im', 'regist', 'voter', 'still', 'voic', 'comelec']
1	0.49584055	b'what happen wala naman masama live stream eh .. ma ok nga yun dayaan im regist voter still voic comelec'
Raw data: Congratulations!!

#Comelec

https://t.co/z1FFCtgB58
Processed data: ['congratul', 'comelec']
1	0.49912039	b'congratul comelec'
Raw data: Grabe talaga ang pinklawan gagawin ang lahat para manalo lang! Buti may hacker nalaman tuloy kung ano ang gag

In [287]:
tweet = 'wala namang masama kung mangampanya siya sa BBM nya! late na nga nakauwi, nakakain na rin tapos makakarinig ka ng '
print(process_tweet(tweet))
y_hat = predict_tweet(tweet, freqs, theta)
print(y_hat)
if y_hat > 0.5:
    print('Positive sentiment')
else: 
    print('Negative sentiment')

['wala', 'namang', 'masama', 'mangampanya', 'bbm', 'nya', 'late', 'nga', 'nakauwi', 'nakakain', 'rin', 'tapo', 'makakarinig']
[[0.49465304]]
Negative sentiment
